### ISSUE TITLE
Quantum Entangled Colonists

### ISSUE THREAD

**Issue by MrSamuelStreamer** [MrSamuelStreamer/GenerationsFlavourPack#35]
See episode 8, towards the end of the episode (currently unedited, timestamps delivered later).

Quibby was attacked by Hornets and brought to the hospital. Several moments later, a trader caravan rescued and delivered a second Quibby to the hospital. Both Quibby's shared everything except for the combat log, however on reloading the Quibby with the combat log switched. Relationship tab had the original Quibby's relationship tab intact along with the new Quibby's relationship also present on the same relationship tab. Hediffs were identical across Quibbys, including pregnancy.

Other observations:
- Reloading appears to shuffle Quibby's log between the two entangled Quibbys
- Quibby's actions (lying down) appears to impact the other Quibby who was teleported to the same spot.

**Comment by keyz182** [comment]
They're gonna have the same reference, which will be why the combat log switches, and actions affect both. As to the _how_ - I'd have to assume the rescue event has a bug where it's either not checking if the chosen rescuee is a valid rescue target, or it's picking from the wrong pool.

**Comment by alt44s** [comment]
I believe this is related to the "[Allies are Helpful](https://steamcommunity.com/sharedfiles/filedetails/?id=3235428952)" mod, where apparently there is a rare bug when reloading a save under specific conditions which causes a pawn to duplicate if they were being rescued by another ally pawn, which would explain the "entangling". 

As for whether this is game-breaking or not, I'm not sure. The few reports I've received about this had no errors and not much to go off of, and my attempts to replicate it at the time weren't successful. 

I _probably_ wouldn't advise keeping the pawn since it's 100% unintended behavior and weird rimworld save wizardry, but I also believe that at any point you'll be able to simply edit the duplicated pawn out of the save file directly, which would be preferable opposed to using devmode to delete them.

**Comment by MrSamuelStreamer** [comment]
Duplicating the character with character editor and saving with that method gives them a unique reference and CE does a good job of handling social linking from scratch, but still has some strange side effects like duplicated relationships that are invalid (two wives in a monogamous ideology, for example). 

Couldn't recreate it at all after quicksave and loading so seems like a freak accident!
